### ISSUE TITLE
Emmet no longer does anything

### ISSUE THREAD

**Issue by manfrancisco** [olrtg/emmet-language-server#9] opened 2023-09-04 07:36 UTC
Emmet completions don't work for me anymore. I installed it with `Mason`, and it was working great, until one day it stopped working. The completions still show up, so if I type `ht` I see a completion that says `html~ Text`, which I don't get if I uninstall it. But if I select the completion it autocompletes to nothing.

I have nothing whatsoever related to `emmet-language-server` in my config. I would assume that was the problem, except that it was working before, so I don't get what changed.

**Comment by olrtg** [comment] 2023-09-04 13:36
Hey! Please check just in case that you're running the latest version of the language server (see #5) and also that you don't have a too-old node version like v12 (see #8).

So from what you're telling me I assume that the language server is attaching but still, can you show me the output of `:LspInfo`? And also in which file type are you trying to use the language server (HTML, jsx, PHP)?

**Comment by manfrancisco** [comment] 2023-09-04 19:27
Node version: `v18.13.0`
emmet-language-server version: `2.1.0`

`:LspInfo`
```
 Client: emmet_language_server (id: 3, bufnr: [5])
 	filetypes:       astro, css, eruby, html, htmldjango, javascriptreact, less, pug, sass, scss, svelte, typescriptreact, vue
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             /home/michael/.local/share/nvim/mason/bin/emmet-language-server --stdio
 
 Other clients that match the filetype: html
```

**Comment by manfrancisco** [comment] 2023-09-04 19:32
Does the ls do any kind of logging? Or is there a debug mode or something I can activate? I'd love to provide you more info.

**Comment by olrtg** [comment] 2023-09-04 23:46
I don't quite remember and I'm far from my computer. If I'm not mistaken it should be `:LspLog` or something like that. The only thing that looks weird for me are those language servers running in single file mode. How come you don't have any config related to this language server? Are you using some automated setup? I'm pretty sure that the problem is related to your setup, not this language server. But still would like to help you.

**Comment by manfrancisco** [comment] 2023-09-05 07:45
I never added any config at all, I just installed it from Mason and it was working, but now it's not. I haven't tried adding any config because it's not clear to me from the examples how to configure it using Lazy, which is what I'm currently using, and since it was working fine before I figured the defaults were fine for me.

**Comment by manfrancisco** [comment] 2023-09-05 07:56
I think I've realized something. I have it installed an two different machines, and it works on one but not the other. It may be that I misremembered and it never actually worked on that second machine. I'll do some digging and try to find out what's different between them.

**Comment by manfrancisco** [comment] 2023-09-05 08:02
Okay I think I figured it out. LuaSnip was causing errors on startup so I removed it from my config. I thought it was just for Lua, but it looks like I was wrong! I guess that's what was doing the actual inserting of text. Lesson learned!

**Comment by olrtg** [comment] 2023-09-05 12:53
Hey! Yeah LuaSnip is an important plugin for snippets stuff, so you'll probably want to have it in your plugin list. And yeah, it's not only for Lua files and it should provide snippets support for all languages. I don't know if it's required for this language server to provide completions for you (since this language server provides snippets at the end of the day) but I don't think so.

**Comment by manfrancisco** [comment] 2023-09-05 17:05
My config is indeed based off of kickstart, but it still wasn't clear to me how to configure this plugin. Regardless, with luasnip installed it seems that no configuration is necessary.

**Comment by olrtg** [comment] 2023-09-05 17:50
Ok ok! So I'm going to close this for now since this is not a problem with the language server. What I didn't get was if now you're able to use the language server after disabling LuaSnip.

**Closed by olrtg** 2023-09-05 17:50 UTC
